# Generated by Django 6.0.4 on 2026-04-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_booking_id_alter_parkinglot_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='working_hours',
            field=models.CharField(blank=True, help_text='e.g., 24/7 or 09:00-21:00', max_length=100, null=True),
        ),
    ]
